import type { ReportDetail } from '@/types/report';

export const demoReports: ReportDetail[] = [
  {
    id: 'demo-report-pothole-001',
    category: 'pothole',
    status: 'in_progress',
    latitude: 42.2139,
    longitude: 20.7397,
    source: 'citizen',
    description: 'Large road-surface damage near a busy junction; vehicles are slowing sharply.',
    confidence: undefined,
    created_at: '2026-05-22T08:12:00.000Z',
    updated_at: '2026-05-22T10:35:00.000Z',
    resolution_note: null,
    rejection_reason: null,
    workflow_events: [
      {
        id: 'demo-event-pothole-created',
        report_id: 'demo-report-pothole-001',
        from_status: null,
        to_status: 'new',
        note: 'Citizen report received through the mobile flow.',
        created_at: '2026-05-22T08:12:00.000Z',
        actor_type: 'system',
        actor_label: 'KoStreet demo',
      },
      {
        id: 'demo-event-pothole-verified',
        report_id: 'demo-report-pothole-001',
        from_status: 'new',
        to_status: 'verified',
        note: 'Municipal intake verified the road defect and location.',
        created_at: '2026-05-22T09:05:00.000Z',
        actor_type: 'municipality',
        actor_label: 'Kosovo municipal staff demo',
      },
      {
        id: 'demo-event-pothole-progress',
        report_id: 'demo-report-pothole-001',
        from_status: 'verified',
        to_status: 'in_progress',
        note: 'Roads/Public Works prepared a repair task.',
        created_at: '2026-05-22T10:35:00.000Z',
        actor_type: 'municipality',
        actor_label: 'Kosovo municipal staff demo',
      },
    ],
  },
  {
    id: 'demo-report-garbage-001',
    category: 'garbage',
    status: 'assigned',
    latitude: 42.2108,
    longitude: 20.7329,
    source: 'citizen',
    description: 'Illegal dumping next to public bins; bags are blocking pedestrian movement.',
    confidence: undefined,
    created_at: '2026-05-22T07:44:00.000Z',
    updated_at: '2026-05-22T09:30:00.000Z',
    resolution_note: null,
    rejection_reason: null,
    workflow_events: [
      {
        id: 'demo-event-garbage-created',
        report_id: 'demo-report-garbage-001',
        from_status: null,
        to_status: 'new',
        note: 'Citizen report received.',
        created_at: '2026-05-22T07:44:00.000Z',
        actor_type: 'system',
        actor_label: 'KoStreet demo',
      },
      {
        id: 'demo-event-garbage-assigned',
        report_id: 'demo-report-garbage-001',
        from_status: 'verified',
        to_status: 'assigned',
        note: 'Sanitation team selected as suggested department.',
        created_at: '2026-05-22T09:30:00.000Z',
        actor_type: 'municipality',
        actor_label: 'Kosovo municipal staff demo',
      },
    ],
  },
  {
    id: 'demo-report-light-001',
    category: 'broken_streetlight',
    status: 'verified',
    latitude: 42.2181,
    longitude: 20.7365,
    source: 'citizen',
    description: 'Streetlight fixture appears damaged near the pedestrian crossing.',
    confidence: undefined,
    created_at: '2026-05-21T19:20:00.000Z',
    updated_at: '2026-05-22T08:25:00.000Z',
    resolution_note: null,
    rejection_reason: null,
    workflow_events: [
      {
        id: 'demo-event-light-created',
        report_id: 'demo-report-light-001',
        from_status: null,
        to_status: 'new',
        note: 'Citizen report received after dark.',
        created_at: '2026-05-21T19:20:00.000Z',
        actor_type: 'system',
        actor_label: 'KoStreet demo',
      },
      {
        id: 'demo-event-light-verified',
        report_id: 'demo-report-light-001',
        from_status: 'new',
        to_status: 'verified',
        note: 'Issue verified for electrical infrastructure review.',
        created_at: '2026-05-22T08:25:00.000Z',
        actor_type: 'municipality',
        actor_label: 'Kosovo municipal staff demo',
      },
    ],
  },
  {
    id: 'demo-report-sidewalk-001',
    category: 'blocked_sidewalk',
    status: 'new',
    latitude: 42.2119,
    longitude: 20.7443,
    source: 'citizen',
    description: 'Construction material is blocking most of the sidewalk near a school route.',
    confidence: undefined,
    created_at: '2026-05-22T11:02:00.000Z',
    updated_at: '2026-05-22T11:02:00.000Z',
    resolution_note: null,
    rejection_reason: null,
    workflow_events: [
      {
        id: 'demo-event-sidewalk-created',
        report_id: 'demo-report-sidewalk-001',
        from_status: null,
        to_status: 'new',
        note: 'Citizen report received and awaiting municipal review.',
        created_at: '2026-05-22T11:02:00.000Z',
        actor_type: 'system',
        actor_label: 'KoStreet demo',
      },
    ],
  },
  {
    id: 'demo-report-sign-001',
    category: 'damaged_sign',
    status: 'resolved',
    latitude: 42.2155,
    longitude: 20.7311,
    source: 'citizen',
    description: 'Bent traffic sign is difficult to read from the right lane.',
    confidence: undefined,
    created_at: '2026-05-20T13:16:00.000Z',
    updated_at: '2026-05-21T15:10:00.000Z',
    resolution_note: 'Damaged sign replaced by Public Works team in the demo scenario.',
    rejection_reason: null,
    workflow_events: [
      {
        id: 'demo-event-sign-created',
        report_id: 'demo-report-sign-001',
        from_status: null,
        to_status: 'new',
        note: 'Citizen report received.',
        created_at: '2026-05-20T13:16:00.000Z',
        actor_type: 'system',
        actor_label: 'KoStreet demo',
      },
      {
        id: 'demo-event-sign-resolved',
        report_id: 'demo-report-sign-001',
        from_status: 'in_progress',
        to_status: 'resolved',
        note: 'Damaged sign replaced by Public Works team in the demo scenario.',
        created_at: '2026-05-21T15:10:00.000Z',
        actor_type: 'municipality',
        actor_label: 'Kosovo municipal staff demo',
      },
    ],
  },
  {
    id: 'demo-report-audit-pothole-001',
    category: 'pothole',
    status: 'verified',
    latitude: 42.2192,
    longitude: 20.7428,
    source: 'street_audit',
    description: 'Demo AI Street Audit scenario flagged a likely pothole for human review.',
    confidence: 0.82,
    created_at: '2026-05-22T09:42:00.000Z',
    updated_at: '2026-05-22T10:12:00.000Z',
    resolution_note: null,
    rejection_reason: null,
    workflow_events: [
      {
        id: 'demo-event-audit-pothole-created',
        report_id: 'demo-report-audit-pothole-001',
        from_status: null,
        to_status: 'new',
        note: 'Demo AI suggestion converted into a municipal review item.',
        created_at: '2026-05-22T09:42:00.000Z',
        actor_type: 'system',
        actor_label: 'KoStreet demo',
      },
      {
        id: 'demo-event-audit-pothole-verified',
        report_id: 'demo-report-audit-pothole-001',
        from_status: 'new',
        to_status: 'verified',
        note: 'Human reviewer accepted the demo suggestion.',
        created_at: '2026-05-22T10:12:00.000Z',
        actor_type: 'municipality',
        actor_label: 'Kosovo municipal staff demo',
      },
    ],
  },
];

export function findDemoReport(reportId: string): ReportDetail | null {
  return demoReports.find((report) => report.id === reportId) ?? null;
}
