import type { AuditSuggestion } from '@/types/detection';

export const demoAuditSuggestions: AuditSuggestion[] = [
  {
    id: 'demo-suggestion-pothole-001',
    audit_run_id: 'demo-audit-run-001',
    category: 'pothole',
    status: 'pending_review',
    latitude: 42.6682,
    longitude: 21.1686,
    confidence: 0.82,
    severity: 'medium',
    description: 'Likely road-surface depression near a vehicle lane.',
    model_name: 'Demo PaliGemma/Gemma review scenario',
    explanation: 'Prepared demo evidence for how a real model suggestion would be reviewed.',
    image_url: null,
    image_attribution: null,
    bounding_box: null,
    created_at: '2026-05-22T09:42:00.000Z',
  },
  {
    id: 'demo-suggestion-garbage-001',
    audit_run_id: 'demo-audit-run-001',
    category: 'garbage',
    status: 'needs_manual_review',
    latitude: 42.6598,
    longitude: 21.1587,
    confidence: 0.76,
    severity: 'medium',
    description: 'Possible illegal dumping next to public bins.',
    model_name: 'Demo PaliGemma/Gemma review scenario',
    explanation: 'Prepared demo scenario for sanitation triage.',
    image_url: null,
    image_attribution: null,
    bounding_box: null,
    created_at: '2026-05-22T09:48:00.000Z',
  },
  {
    id: 'demo-suggestion-sidewalk-001',
    audit_run_id: 'demo-audit-run-001',
    category: 'blocked_sidewalk',
    status: 'pending_review',
    latitude: 42.6609,
    longitude: 21.1701,
    confidence: 0.71,
    severity: 'low',
    description: 'Possible pedestrian obstruction along a sidewalk segment.',
    model_name: 'Demo PaliGemma/Gemma review scenario',
    explanation: 'Prepared demo scenario for human verification.',
    image_url: null,
    image_attribution: null,
    bounding_box: null,
    created_at: '2026-05-22T09:55:00.000Z',
  },
];
