import type { AuditSuggestion } from '@/types/detection';
import { DEMO_AUDIT_RUN_ID } from '@/demo/demoAuditScanPath';
import { boundingBoxToRegion } from '@/utils/detectionRegions';

export const demoAuditSuggestions: AuditSuggestion[] = [
  {
    id: 'demo-suggestion-pothole-001',
    audit_run_id: DEMO_AUDIT_RUN_ID,
    category: 'pothole',
    status: 'pending_review',
    latitude: 42.2141,
    longitude: 20.7403,
    confidence: 0.82,
    severity: 'high',
    description: 'Likely road-surface depression near a vehicle lane.',
    model_name: 'Demo PaliGemma/Gemma review scenario',
    explanation: 'Prepared demo evidence for how a real model suggestion would be reviewed.',
    image_url: '/demo/audit/pothole_01.jpg',
    frame_image_url: '/demo/audit/pothole_01.jpg',
    image_attribution: 'Demo Street View frame',
    detection_regions: [boundingBoxToRegion({ x: 0.43, y: 0.59, width: 0.22, height: 0.18 })],
    frame_index: 4,
    heading: 50,
    pitch: 0,
    created_at: '2026-05-22T09:42:00.000Z',
  },
  {
    id: 'demo-suggestion-garbage-001',
    audit_run_id: DEMO_AUDIT_RUN_ID,
    category: 'garbage',
    status: 'needs_manual_review',
    latitude: 42.21485,
    longitude: 20.74105,
    confidence: 0.76,
    severity: 'medium',
    description: 'Possible illegal dumping next to public bins.',
    model_name: 'Demo PaliGemma/Gemma review scenario',
    explanation: 'Prepared demo scenario for sanitation triage.',
    image_url: '/demo/audit/garbage_01.jpg',
    frame_image_url: '/demo/audit/garbage_01.jpg',
    image_attribution: 'Demo Street View frame',
    detection_regions: [boundingBoxToRegion({ x: 0.31, y: 0.56, width: 0.24, height: 0.2 })],
    frame_index: 9,
    heading: 65,
    pitch: 0,
    created_at: '2026-05-22T09:48:00.000Z',
  },
  {
    id: 'demo-suggestion-sidewalk-001',
    audit_run_id: DEMO_AUDIT_RUN_ID,
    category: 'blocked_sidewalk',
    status: 'pending_review',
    latitude: 42.21535,
    longitude: 20.74155,
    confidence: 0.71,
    severity: 'low',
    description: 'Possible pedestrian obstruction along a sidewalk segment.',
    model_name: 'Demo PaliGemma/Gemma review scenario',
    explanation: 'Prepared demo scenario for human verification.',
    image_url: '/demo/audit/sidewalk_01.jpg',
    frame_image_url: '/demo/audit/sidewalk_01.jpg',
    image_attribution: 'Demo Street View frame',
    detection_regions: [boundingBoxToRegion({ x: 0.25, y: 0.52, width: 0.22, height: 0.16 })],
    frame_index: 13,
    heading: 77,
    pitch: 0,
    created_at: '2026-05-22T09:55:00.000Z',
  },
];

export function demoSuggestionImageUrl(suggestion: AuditSuggestion): string | null {
  return suggestion.frame_image_url ?? suggestion.image_url ?? null;
}
